spring:
  application:
    name: backend
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_SERVER_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  servlet:
    context-path: /api/v1
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}
springdoc:
  swagger-ui:
    url: /openapi.yml
